import React,{useState,useEffect} from 'react';
import {Eye,Activity,GitBranch,Clock,Terminal,RefreshCw,Search,AlertTriangle,Check} from 'lucide-react';
import './directions.css';
import './dark-dashboard.css';
import {previewApi} from './preview/api';
const preview=import.meta.env.VITE_STATIC_PREVIEW==='true';
const elapsed=n=>n>=1000?(n/1000).toFixed(2)+'s':Math.round(n||0)+'ms';
const cost=n=>'$'+Number(n||0).toFixed(6);
export function DarkDashboard(){
 const[traces,setTraces]=useState([]),[stats,setStats]=useState({}),[services,setServices]=useState([]),[detail,setDetail]=useState(null),[selected,setSelected]=useState(''),[focus,setFocus]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[key,setKey]=useState(''),[status,setStatus]=useState(''),[service,setService]=useState(''),[search,setSearch]=useState(''),[view,setView]=useState('Overview'),[last,setLast]=useState(null);
 async function api(path,signal){if(preview)return previewApi(path);const r=await fetch('/api'+path,{signal,headers:key?{Authorization:'Bearer '+key}:{}});if(!r.ok)throw Error(r.status===401?'Enter your API key to connect.':'API request failed ('+r.status+').');return r.json();}
 async function load(signal){try{const q='?days=7'+(status?'&status='+status:'')+(service?'&service='+encodeURIComponent(service):'');const[t,s,v]=await Promise.all([api('/traces'+q,signal),api('/stats'+q,signal),api('/services',signal)]);setTraces(t.traces);setStats(s.summary);setServices(v.services);setError('');setLast(new Date());if(t.traces.length)setSelected(previous=>previous||(t.traces.find(x=>x.status==='ERROR')||t.traces[0])._id);}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{const c=new AbortController();load(c.signal);const timer=preview?null:setInterval(()=>load(c.signal),5000);return()=>{c.abort();clearInterval(timer);};},[status,service,key]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();api('/traces/'+selected,c.signal).then(d=>{setDetail(d);setFocus(previous=>d.spans.find(s=>s.span_id===previous?.span_id)||d.spans.find(s=>s.status==='ERROR'&&s.parent_span_id)||d.spans.find(s=>!s.parent_span_id)||d.spans[0]);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[selected,traces,key]);
 const runs=traces.filter(t=>(t.name+' '+t._id+' '+t.service).toLowerCase().includes(search.toLowerCase()));
 const total=stats.total||0,rate=total?Math.round(stats.success/total*100):null;
 const start=detail?Math.min(...detail.spans.map(s=>Date.parse(s.started_at))):0,end=detail?Math.max(...detail.spans.map(s=>Date.parse(s.ended_at))):0,range=Math.max(1,end-start);
 const ordered=[];function children(parent,depth=0,seen=new Set()){for(const s of detail?.spans.filter(s=>s.parent_span_id===parent)||[]){if(seen.has(s.span_id))continue;seen.add(s.span_id);ordered.push({...s,depth});children(s.span_id,depth+1,seen);}}if(detail){children(null);for(const s of detail.spans)if(!ordered.some(x=>x.span_id===s.span_id))ordered.push({...s,depth:0});}
 const failed=detail?.spans.filter(s=>s.status==='ERROR'&&s.parent_span_id)||[],root=detail?.spans.find(s=>!s.parent_span_id);
 const samples=[...traces].reverse(),max=Math.max(1,...samples.map(t=>t.duration_ms));
 return <div className={'direction direction-2 shipped-dark view-'+view.toLowerCase().replaceAll(' ','-')}><aside className="d-dark-side"><a className="direction-logo" href={import.meta.env.BASE_URL} aria-label="Loupe home"><span className="blinking-eye"><Eye size={27}/></span>loupe<span className="logo-dot">.</span></a><span className="d-workspace">{preview?'DEMO WORKSPACE':'LOCAL WORKSPACE'}</span>{[['Overview',Activity],['Trace explorer',GitBranch],['Latency',Clock],['SDK exports',Terminal]].map(([label,Icon])=><button className={view===label?'d-nav-selected':''} key={label} onClick={()=>setView(label)}><Icon size={17}/>{label}</button>)}<div className="d-bottom"><i className={error?'red':''}/>{error?'Connection issue':preview?'Demo preview':'API connected'}<small>{preview?'Recorded local traces · read only':'No deployment configured'}</small></div></aside><main className="d-dark-main"><div className="d-dark-top"><span>Observability / {view}</span><span><i/>{preview?'Recorded demo':last?'Updated '+last.toLocaleTimeString():'Connecting'}<button onClick={()=>load()} aria-label="Refresh traces"><RefreshCw size={13}/></button></span></div><div className="d-dark-heading"><div><p className="d-kicker">AGENT OBSERVABILITY</p><h1>{view==='Overview'?'Agent health, at a glance.':view==='Trace explorer'?'Follow the work.':view==='Latency'?'Where the time goes.':'Instrumentation, without friction.'}</h1><p>{service||'All services'} <span>/</span> Last 7 days <span>/</span> {preview?'demo environment':'local environment'}</p></div><div className="d-green-label"><i className={error?'red':''}/>{error?'Connection issue':preview?'Static demo data':'5s live refresh'}</div></div>
 {error&&<div className="dark-error" role="alert"><AlertTriangle size={16}/>{error}<input type="password" aria-label="API key" placeholder="API key (memory only)" onChange={e=>setKey(e.target.value)}/></div>}
 <div className="d-dark-metrics"><div><span>Runs observed</span><b>{total}<small>{traces.reduce((n,t)=>n+t.span_count,0)} listed spans</small></b></div><div><span>Success rate</span><b>{rate===null?'—':rate}<small>{rate===null?'':'%'}</small></b><em>{stats.errors||0} failed · {stats.incomplete||0} incomplete</em></div><div><span>P95 wall time</span><b>{Math.round(stats.p95?.[0]||0)}<small>ms</small></b><em>Approximate percentile</em></div><div><span>Known token cost</span><b className="dark-cost">{cost(stats.known_cost)}</b><em>{stats.unpriced||0} unpriced LLM spans</em></div></div>
 <div className="dark-filter"><label><Search size={14}/><input aria-label="Search traces" placeholder="Search runs, service or trace ID" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>OK</option><option>ERROR</option><option>INCOMPLETE</option></select><select aria-label="Service filter" value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{services.map(s=><option key={s}>{s}</option>)}</select></div>
 {view==='SDK exports'?<section className="dark-sdk"><Terminal size={24}/><h2>Connect a Python agent</h2><p>Non-blocking batched span export. Capture metadata, not prompts.</p><pre>{`from loupe import configure, trace, patch_openai\n\nclient = configure(service_name="my-agent")\npatch_openai()\n\n@trace("agent run")\ndef run():\n    return your_agent()\n\nrun()\nclient.flush()\nclient.close()`}</pre><p>Export diagnostics live in <code>client.diagnostics</code>. This dashboard does not infer queue loss from ingested spans. Streaming calls remain uninstrumented in v0.1.</p></section>:<div className="d-dark-grid"><section className="d-chart"><div className="d-section-title">Run latency <span>{samples.length} observed samples · milliseconds</span></div>{samples.length?<><svg viewBox="0 0 600 130" className="d-spark" role="img" aria-label="Observed run latency"><defs><linearGradient id="darkfill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="currentColor" stopOpacity=".27"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs>{[25,60,95].map(y=><line key={y} x1="0" x2="600" y1={y} y2={y} stroke="currentColor" opacity=".14"/>)}<polygon fill="url(#darkfill)" points={'0,130 '+samples.map((t,i)=>`${i*600/Math.max(1,samples.length-1)},${115-t.duration_ms/max*90}`).join(' ')+' 600,130'}/><polyline stroke="currentColor" strokeWidth="2" fill="none" points={samples.map((t,i)=>`${i*600/Math.max(1,samples.length-1)},${115-t.duration_ms/max*90}`).join(' ')}/></svg><div className="d-axis"><span>Oldest listed run</span><span>Peak {elapsed(max)}</span><span>Newest</span></div></>:<p className="dark-empty">Run an instrumented agent to record latency.</p>}<div className="d-run-counts"><span><i/>{stats.success||0} successful</span><span><i className="red"/>{stats.errors||0} failed</span><span>{((stats.input_tokens||0)+(stats.output_tokens||0)).toLocaleString()} recorded tokens</span></div></section>
 <section className="d-dark-incident"><span className="d-kicker">SELECTED RUN / FAILURE POINT</span><h2>{failed[0]?.name.replace('execute_tool ','')||root?.name||'No run selected'}</h2><p>{failed.length?failed.length+' failed child span'+(failed.length===1?'':'s')+' in this run.':'No failed child spans recorded.'}</p><div>{failed.length?<AlertTriangle size={26}/>:<Check size={26}/>}<b>{failed[0]?.attributes['error.type']||'No error'}</b></div><small>{detail?detail.trace_id:'Select a run below'}</small></section>
 <section className="dark-run-panel"><div className="d-section-title">Recent traces <span>{runs.length} listed · newest first</span></div><div className="dark-table-scroll"><table className="d-table"><thead><tr><th>Run</th><th>Status</th><th>Latency</th><th>Spans</th><th>Known cost</th></tr></thead><tbody>{runs.map(t=><tr key={t._id} className={t._id===selected?'chosen':''}><td><button className="dark-run" onClick={()=>{setSelected(t._id);setFocus(null);}}>{t.name}</button><small>{t._id.slice(0,16)} · {t.service}</small></td><td><span className={'d-tag '+(t.status==='ERROR'?'red':'green')}><i/>{t.status}</span></td><td className="d-mono">{elapsed(t.duration_ms)}</td><td className="d-mono">{t.span_count}</td><td className="d-mono">{cost(t.known_cost)}{t.unpriced>0&&<small>{t.unpriced} unpriced</small>}</td></tr>)}</tbody></table></div>{!runs.length&&<p className="dark-empty">{loading?'Connecting…':traces.length?'No matching traces.':'No traces yet. Run python3 demo/agent.py.'}</p>}</section>
 <section className="dark-inspect"><div className="d-waterfall"><div className="d-section-title">Span waterfall <span>{detail?elapsed(range)+' total':'Select a trace'}</span></div><h3>{root?.name||'Run detail'}</h3><p className="d-id">{detail?.trace_id}</p><div className="d-ruler"><span>0</span><span>{elapsed(range/2)}</span><span>{elapsed(range)}</span></div>{ordered.map(s=><button key={s.span_id} className={'d-span '+(focus?.span_id===s.span_id?'span-focused':'')} onClick={()=>setFocus(s)} aria-label={'Inspect span '+s.name}><span style={{paddingLeft:s.depth*12}}><i className={s.status==='ERROR'?'red':''}/>{s.name.replace('execute_tool ','')}</span><div className="d-track"><b className={s.status==='ERROR'?'red':''} style={{left:(Date.parse(s.started_at)-start)/range*100+'%',width:Math.max(1,s.duration_ms/range*100)+'%'}}/></div><small>{elapsed(s.duration_ms)}</small></button>)}{focus&&<><div className="dark-span-heading"><b>{focus.name}</b><span>{focus.status}</span></div><div className="d-attributes"><span>Span ID</span><b>{focus.span_id}</b><span>Parent ID</span><b>{focus.parent_span_id||'Root span'}</b><span>Kind</span><b>{focus.kind}</b><span>Cost estimate</span><b>{focus.cost_usd===null?(focus.attributes['gen_ai.request.model']?'Unpriced':'Not an LLM span'):cost(focus.cost_usd)}</b>{Object.entries(focus.attributes).map(([k,v])=><React.Fragment key={k}><span>{k}</span><b>{String(v)}</b></React.Fragment>)}</div></>}</div></section></div>}
 <p className="dark-footer">Known costs are token estimates, not invoices. Unknown models remain unpriced. Local demo failures are deliberate test cases.</p></main></div>;
}
