import React,{useEffect,useState} from 'react';
import {Eye,Activity,ArrowUpRight,Terminal,Search,ChevronRight,Settings,Command,Clock,GitBranch,AlertTriangle,Check} from 'lucide-react';
import './directions.css';
const elapsed=n=>Math.round(n)+'ms';
export function Directions(){
 const params=new URLSearchParams(location.search);const variant=Number(params.get('dark'))||0;const choice=variant?2:Number(params.get('direction'))||1;
 const [traces,setTraces]=useState([]),[stats,setStats]=useState(null),[detail,setDetail]=useState(null);
 useEffect(()=>{Promise.all([fetch('/api/traces').then(r=>r.json()),fetch('/api/stats').then(r=>r.json())]).then(async([t,s])=>{setTraces(t.traces);setStats(s.summary);const failed=t.traces.find(t=>t.status==='ERROR')||t.traces[0];if(failed)setDetail(await fetch('/api/traces/'+failed._id).then(r=>r.json()));});},[]);
 if(!stats)return <div>Loading real local traces…</div>;
 const total=stats.total,rate=total?Math.round(stats.success/total*100):0;
 const root=detail?.spans.find(s=>!s.parent_span_id),start=detail?Math.min(...detail.spans.map(s=>Date.parse(s.started_at))):0,range=detail?Math.max(...detail.spans.map(s=>Date.parse(s.ended_at)))-start:1;
 const ordered=detail?[root,...detail.spans.filter(s=>s!==root)].filter(Boolean):[];
 const logo=<a className="direction-logo" href="/"><span className="blinking-eye"><Eye size={27}/></span>loupe<span className="logo-dot">.</span></a>;
 const waterfall=<div className="d-waterfall"><div className="d-section-title"><span>Failure inspection</span><span className="d-tag red">TimeoutError</span></div><h3>documentation agent</h3><p className="d-id">{detail?.trace_id}</p><div className="d-ruler"><span>0</span><span>{elapsed(range/2)}</span><span>{elapsed(range)}</span></div>{ordered.map(s=><div key={s.span_id} className="d-span"><span style={{paddingLeft:s.parent_span_id?16:0}}><i className={s.status==='ERROR'?'red':''}/>{s.name.replace('execute_tool ','')}</span><div className="d-track"><b className={s.status==='ERROR'?'red':''} style={{left:(Date.parse(s.started_at)-start)/range*100+'%',width:Math.max(2,s.duration_ms/range*100)+'%'}}/></div><small>{elapsed(s.duration_ms)}</small></div>)}<div className="d-failure-note"><AlertTriangle size={15}/><span>validate_sources timed out<span className="d-fine">Deliberate demo failure. Parent run marked ERROR.</span></span></div><div className="d-attributes"><span>error.type</span><b>TimeoutError</b><span>service.name</span><b>docs-agent</b><span>Capture policy</span><b>Metadata only</b></div></div>;
 const rows=<table className="d-table"><thead><tr><th>Run</th><th>Status</th><th>Latency</th><th>Spans</th><th>Started</th></tr></thead><tbody>{traces.map((t,i)=><tr key={t._id} className={i===0?'chosen':''}><td><strong>documentation agent</strong><small>{t._id.slice(0,16)} · docs-agent</small></td><td><span className={'d-tag '+(t.status==='ERROR'?'red':'green')}><i/>{t.status==='ERROR'?'Error':'OK'}</span></td><td className="d-mono">{elapsed(t.duration_ms)}</td><td className="d-mono">{t.span_count}</td><td className="d-mono">{new Date(t.started_at).toLocaleTimeString('en-US',{hour12:false})}</td></tr>)}</tbody></table>;
 const spark=<svg viewBox="0 0 600 120" className="d-spark" aria-label="Observed run durations"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="currentColor" stopOpacity=".25"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs>{[30,60,90].map(y=><line key={y} x1="0" x2="600" y1={y} y2={y} stroke="currentColor" opacity=".12"/>)}<polygon fill="url(#fill)" points={'0,120 '+[...traces].reverse().map((t,i)=>`${i*600/Math.max(1,traces.length-1)},${110-t.duration_ms/Math.max(...traces.map(x=>x.duration_ms))*90}`).join(' ')+' 600,120'}/><polyline fill="none" stroke="currentColor" strokeWidth="2" points={[...traces].reverse().map((t,i)=>`${i*600/Math.max(1,traces.length-1)},${110-t.duration_ms/Math.max(...traces.map(x=>x.duration_ms))*90}`).join(' ')}/></svg>;
 return <div className={'direction direction-'+choice+(variant?' dark-variant-'+variant:'')}>
 {choice===1?<><nav className="d-console-nav">{logo}<span className="d-workspace">local / docs-agent <ChevronRight size={12}/></span><b>Traces</b><span>Metrics</span><span>Exports</span><div className="d-nav-right"><i/> API connected <Settings size={17}/></div></nav><div className="d-console-toolbar"><div><p className="d-kicker">01 / OBSERVABILITY CONSOLE</p><h1>Trace explorer</h1></div><div className="d-query"><Search size={15}/> service:docs-agent <b>Last 7 days</b></div></div><div className="d-inline-metrics"><span><b>{total}</b> runs</span><span><b>{rate}%</b> success</span><span><b>{elapsed(stats.p95?.[0]||0)}</b> p95 latency</span><span><b>{stats.errors}</b> errors</span><span><b>0</b> LLM tokens <small>tool-only demo</small></span></div><div className="d-console-main"><section><div className="d-section-title">Recent runs <span>Newest first · 8 recorded</span></div>{rows}<div className="d-console-bottom"><Terminal size={13}/><span>30 spans exported · 0 dropped · bounded batch queue</span></div></section><section>{waterfall}<div className="d-code"><span>Python / instrumentation</span><pre><em>@trace</em>("documentation agent"){'\n'}<em>def</em> run(question):{'\n'}    docs = search_docs(question){'\n'}    validate_sources(docs){'\n'}    <em>return</em> compose_answer(docs)</pre></div></section></div></>:
 choice===2?<><aside className="d-dark-side">{logo}<span className="d-workspace">LOCAL WORKSPACE</span><b><Activity size={17}/> Overview</b><span><GitBranch size={17}/> Trace explorer</span><span><Clock size={17}/> Latency</span><span><Terminal size={17}/> SDK exports</span><div className="d-bottom"><i/> All systems local<small>No deployment configured</small></div></aside><main className="d-dark-main"><div className="d-dark-top"><span>Observability / Overview</span><span><Command size={14}/> K <i/> Live</span></div><div className="d-dark-heading"><div><p className="d-kicker">{variant===1?'A / LEFT-RAIL WORKSPACE':variant===2?'B / CHART-FIRST CONTROL ROOM':variant===3?'C / TRACE TERMINAL':'D / TOP-NAV SPLIT DESK'}</p><h1>{variant===3?'Trace terminal':variant===4?'Every span. One workspace.':'Agent health, at a glance.'}</h1><p>docs-agent <span> / </span> Python SDK <span> / </span> local environment</p></div><div className="d-green-label"><i/> Ingestion healthy</div></div><div className="d-dark-metrics"><div><span>Runs observed</span><b>{total}<small>30 spans</small></b></div><div><span>Success rate</span><b>{rate}<small>%</small></b><em>{stats.errors} deliberate failures</em></div><div><span>P95 wall time</span><b>{Math.round(stats.p95?.[0]||0)}<small>ms</small></b></div><div><span>Export loss</span><b>0<small>dropped</small></b><em>Verified in this demo</em></div></div><div className="d-dark-grid"><section className="d-chart"><div className="d-section-title">Run latency <span>8 observed samples</span></div>{spark}<div className="d-axis"><span>Run 1</span><span>Chronological executions</span><span>Run 8</span></div><div className="d-run-counts"><span><i/> 6 successful</span><span><i className="red"/> 2 failed</span><span>Local tool execution · no LLM calls</span></div></section><section className="d-dark-incident"><span className="d-kicker">FAILURE CLUSTER</span><h2>Source validation</h2><p>Two runs stopped at the same tool.</p><div><AlertTriangle size={28}/><b>TimeoutError</b><span>validate_sources</span></div><small>Intentional failure scenarios, not production incidents.</small></section><section>{rows}</section><section>{waterfall}</section><section className="d-terminal-extra"><div className="d-section-title">Event ledger <span>Actual span metadata</span></div>{detail?.spans.map(s=><div className="d-ledger" key={s.span_id}><span>{new Date(s.started_at).toLocaleTimeString("en-US",{hour12:false})}</span><span>{s.kind}</span><b>{s.name}</b><span className={s.status==="ERROR"?"d-ledger-error":""}>{s.status}</span><span>{s.span_id}</span></div>)}</section></div></main></>:
 <><div className="d-editorial-top">{logo}<span>Traces & intelligence</span><span className="d-editorial-status"><i/> Local development</span></div><div className="d-editorial-heading"><p className="d-kicker">03 / THE RUN JOURNAL</p><h1>Small details.<br/><em>The whole picture.</em></h1><div><p>An instrumented account of your agent's work.<br/>What ran, what failed, and where the time went.</p><span>docs-agent · Last 7 days · {total} runs</span></div></div><div className="d-editorial-metrics"><div><span>01 / Volume</span><b>{total}</b><small>Observed agent runs</small></div><div><span>02 / Reliability</span><b>{rate}<em>%</em></b><small>6 completed / 2 deliberate timeouts</small></div><div><span>03 / Pace</span><b>{Math.round(stats.p95?.[0]||0)}<em>ms</em></b><small>95th percentile wall time</small></div><div><span>04 / Cost</span><b>$0</b><small>Local tools · no provider inference</small></div></div><div className="d-editorial-body"><section><div className="d-section-title">The latest runs <ArrowUpRight size={18}/></div>{rows}</section><section className="d-editorial-story"><p className="d-kicker">UNDER THE LENS</p><h2>One failure.<br/>Three spans.<br/>Nothing hidden.</h2>{waterfall}<p className="d-editorial-foot">Metadata, not messages.<br/>Prompts and private outputs stay out of the trace.</p></section></div></>}
 </div>;
}
