import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,Search,ArrowUpRight,ChevronRight,Clock,CheckCircle2,Layers,RefreshCw,AlertTriangle,Terminal,Eye} from 'lucide-react';
import './style.css';
import {Directions} from './directions.jsx';
const money=n=>n===null?'Unpriced':'$'+Number(n||0).toFixed(6);
const ms=n=>n>1000?(n/1000).toFixed(2)+'s':Math.round(n||0)+'ms';
function App(){
 const [traces,setTraces]=useState([]),[summary,setSummary]=useState({}),[daily,setDaily]=useState([]),[services,setServices]=useState([]),[filter,setFilter]=useState(''),[service,setService]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[focus,setFocus]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[key,setKey]=useState(''),[last,setLast]=useState(null);
 async function api(path,signal){const r=await fetch('/api'+path,{headers:key?{Authorization:'Bearer '+key}:{},signal});if(!r.ok)throw new Error(r.status===401?'API key required. Enter it in the connection panel.':'Could not load traces ('+r.status+').');return r.json();}
 async function load(signal){try{const query='?days=7'+(filter?'&status='+filter:'')+(service?'&service='+encodeURIComponent(service):'');const [t,s,v]=await Promise.all([api('/traces'+query,signal),api('/stats'+query,signal),api('/services',signal)]);setTraces(t.traces);setSummary(s.summary);setDaily(s.daily);setServices(v.services);setLast(new Date());setError('');}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();load(controller.signal);const timer=setInterval(()=>load(controller.signal),5000);return()=>{clearInterval(timer);controller.abort();};},[filter,service,key]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();api('/traces/'+selected,c.signal).then(d=>{setDetail(d);setFocus(d.spans.find(s=>s.status==='ERROR')||d.spans[0]);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[selected,key,traces]);
 const total=summary.total||0, visible=traces.filter(t=>(t.name+' '+t._id+' '+t.service).toLowerCase().includes(search.toLowerCase()));
 const base=detail?Math.min(...detail.spans.map(s=>Date.parse(s.started_at))):0,end=detail?Math.max(...detail.spans.map(s=>Date.parse(s.ended_at))):0,range=Math.max(1,end-base);
 const ordered=[];function walk(parent,seen=new Set()){for(const span of detail?.spans.filter(s=>s.parent_span_id===parent)||[]){if(seen.has(span.span_id))continue;seen.add(span.span_id);ordered.push(span);walk(span.span_id,seen);}}if(detail){walk(null);for(const s of detail.spans)if(!ordered.some(x=>x.span_id===s.span_id))ordered.push(s);}
 function depth(span,seen=new Set()){if(!span.parent_span_id||seen.has(span.span_id))return 0;seen.add(span.span_id);const parent=detail.spans.find(s=>s.span_id===span.parent_span_id);return parent?1+depth(parent,seen):0;}
 return <><aside><a className="brand" href="/" aria-label="Loupe home"><span className="blinking-eye"><Eye size={25}/></span><b>loupe<span>.</span></b></a><div className="workspace"><span className="avatar">L</span><div>Local workspace<small>Development environment</small></div></div><p className="nav-label">OBSERVABILITY</p><div className="nav active"><Activity size={17}/>Traces<span>{total}</span></div><div className="side-note"><Terminal size={20}/><b>See what your agent did.</b><p>Trace the work. Find the failure. Understand the cost.</p><code>pip install ./sdk</code></div><div className="side-bottom"><i/> Local API <small>No deployment configured</small></div></aside>
 <main><header><div className="crumb">Workspace <ChevronRight size={14}/> <b>Traces</b></div><span className="live"><i/> {error?'Connection issue':'Live · 5s refresh'}</span></header><section className="heading"><div><p className="eyebrow">AGENT OBSERVABILITY</p><h1>Every run, in focus.</h1><p className="sub">Inspect latency, token usage and failures across your agents.</p></div><button onClick={()=>load()}><RefreshCw size={15}/> Refresh</button></section>
 {error&&<div role="alert" className="error"><AlertTriangle size={16}/>{error}<input aria-label="API key" type="password" placeholder="API key (memory only)" onChange={e=>setKey(e.target.value)}/></div>}
 <div className="metrics"><Metric icon={<Layers/>} title="Total runs" value={total} hint="Last 7 days"/><Metric icon={<CheckCircle2/>} title="Success rate" value={total?(100*summary.success/total).toFixed(1)+'%':'—'} hint={(summary.errors||0)+' failed · '+(summary.incomplete||0)+' incomplete'}/><Metric icon={<Clock/>} title="P95 latency" value={ms(summary.p95?.[0])} hint="Trace wall time · approximate"/><Metric icon={<ArrowUpRight/>} title="Known token cost" value={money(summary.known_cost)} hint={(summary.unpriced||0)+' unpriced · '+money(total?summary.known_cost/total:0)+'/run'}/></div>
 <section className="panel trend"><div><p className="eyebrow">USAGE OVER TIME</p><h3>Runs by day <span>UTC</span></h3></div><div className="bars">{daily.length?daily.map(d=><div className="day" key={d._id}><b>{d.runs}</b><div style={{height:Math.max(8,60*d.runs/Math.max(...daily.map(x=>x.runs)))}}/><small>{d._id.slice(5)}</small><span>{money(d.known_cost)}</span></div>):<span className="muted">Run the demo agent to start recording.</span>}</div><div className="token-note"><b>{((summary.input_tokens||0)+(summary.output_tokens||0)).toLocaleString()}</b> tokens recorded<small>Input + output, raw usage retained</small></div></section>
 <section className="panel table-panel"><div className="table-heading"><h2>Recent traces <span>{visible.length}</span></h2><div className="filters"><label><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search runs or trace IDs" aria-label="Search traces"/></label><select aria-label="Status filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option>OK</option><option>ERROR</option><option>INCOMPLETE</option></select><select aria-label="Service filter" value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{services.map(s=><option key={s}>{s}</option>)}</select></div></div><div className="table-scroll"><table><thead><tr><th>Run / trace ID</th><th>Service</th><th>Status</th><th>Duration</th><th>Tokens</th><th>Known cost</th><th>Started</th><th/></tr></thead><tbody>{visible.map(t=><tr key={t._id}><td><button className="run-link" onClick={()=>{setDetail(null);setSelected(t._id);}}>{t.name}</button><small className="mono">{t._id.slice(0,16)}… · {t.span_count} spans</small></td><td>{t.service}</td><td><Badge status={t.status}/></td><td className="mono">{ms(t.duration_ms)}</td><td className="mono">{t.input_tokens+t.output_tokens}</td><td className="mono">{money(t.known_cost)}{t.unpriced>0&&<small>{t.unpriced} unpriced</small>}</td><td>{new Date(t.started_at).toLocaleTimeString()}</td><td><button aria-label={'Inspect '+t.name} onClick={()=>{setDetail(null);setSelected(t._id);}} className="icon-button"><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div>{!visible.length&&<div className="empty"><Activity size={30}/><h3>{loading?'Connecting to Loupe…':traces.length?'No matching traces':'Your first trace starts here.'}</h3><p>Run <code>python3 demo/agent.py</code> with the API running.</p></div>}<footer>Showing latest 100 traces · last 7 days<span>{last?'Updated '+last.toLocaleTimeString():'Waiting for API'}</span></footer></section>
 <p className="disclaimer">Token costs are estimates, not invoices. Unknown models remain unpriced. Demo inference is local and labeled.</p></main>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="drawer" onKeyDown={e=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll('button,input,select,[tabindex]')];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}} role="dialog" aria-modal="true" aria-label="Trace waterfall" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">TRACE DETAIL</p><h2>{detail?.spans.find(s=>!s.parent_span_id)?.name||'Loading trace…'}</h2><code>{selected}</code></div><button autoFocus onClick={()=>setSelected(null)} aria-label="Close trace">Close</button></div>{detail&&<><div className="waterfall-header"><b>Span waterfall</b><span>{ms(range)} total · {detail.spans.length} spans</span></div><div className="waterfall">{ordered.map(s=><button key={s.span_id} className={'span-row '+(focus?.span_id===s.span_id?'selected':'')} onClick={()=>setFocus(s)}><div className="span-name" style={{paddingLeft:depth(s)*12}}><i className={s.status==='ERROR'?'bad':''}/><span>{s.name}</span></div><div className="track"><div className={'span-bar '+(s.status==='ERROR'?'bad':'')} style={{left:((Date.parse(s.started_at)-base)/range*100)+'%',width:Math.max(.7,s.duration_ms/range*100)+'%'}}/></div><span className="mono duration">{ms(s.duration_ms)}</span></button>)}</div>{focus&&<div className="span-info"><div><h3>{focus.name}</h3><Badge status={focus.status}/></div><dl><dt>Span ID</dt><dd>{focus.span_id}</dd><dt>Parent</dt><dd>{focus.parent_span_id||'Root span'}</dd><dt>Kind</dt><dd>{focus.kind}</dd><dt>Known cost</dt><dd>{money(focus.cost_usd)}</dd><dt>Pricing</dt><dd>{focus.pricing_reason} · {focus.pricing_version}</dd></dl><h4>Attributes</h4>{Object.entries(focus.attributes).length?<dl>{Object.entries(focus.attributes).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{String(v)}</dd></React.Fragment>)}</dl>:<p className="muted">No attributes captured.</p>}</div>}</>}</section></div>}
 </>;
}
function Metric({icon,title,value,hint}){return <div className="metric"><div>{title}<span>{icon}</span></div><strong>{value}</strong><small>{hint}</small></div>}
function Badge({status}){return <span className={'badge '+status.toLowerCase()}><i/>{status==='OK'?'Success':status==='ERROR'?'Error':'Incomplete'}</span>}
createRoot(document.getElementById('root')).render(new URLSearchParams(location.search).has('direction')?<Directions/>:<App/>);
